### ISSUE TITLE
Transfer to Quelpa organization?

### ISSUE THREAD

**Issue by jcs090218** [quelpa/quelpa-leaf#1]
`leaf` is another alternative to `use-package`. This is basically ported from `quelpa-use-package`.

@steckerhalter I think this repo should be under quelpa? Would you mind if I transfer this repository to the organization?

Thanks!

**Comment by steckerhalter** [comment]
@jcs090218 no that would be fine

**Comment by jcs090218** [comment]
@steckerhalter Thanks! I don't think I have the permission to create the public repository in the organization (transfer). Can you give me the permission to do so?

**Comment by steckerhalter** [comment]
ok to transfer :+1:

**Comment by jcs090218** [comment]
I don't think I have the permission to transfer. Can you give me the permission to create public repository? So then I can transfer it to the organization. Thanks!

**Comment by jcs090218** [comment]
@steckerhalter I don't think I have the permission to transfer. Can you give me the permission to create public repository? So then I can transfer it to the organization. Thanks!

**Comment by steckerhalter** [comment]
does it work now?

**Comment by jcs090218** [comment]
Yeah! It works! Thanks! Close this now! ;)
